[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#7b2cbf"
backgroundColor = "#0a192f"
secondaryBackgroundColor = "#172a45"
textColor = "#FFFFFF"

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000
gatherUsageStats = false